### ISSUE TITLE
Arbitrary radii for spheres

### ISSUE THREAD

**Issue by benneti** [JuliaNLSolvers/ManifoldProjections.jl#2]
As discussed at  [DifferentialEquations.jl #389](https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/389) it might be useful to change the Sphere class to include a radius
```
struct Sphere{T} <: Manifold where {T <: Real}
    r::T
end
Sphere() = Sphere(1)
retract!(S::Sphere, x) = (x .= x .* (S.r / norm(x)))
```
I think this might be a good idea as it does not add much complexity and eases the use of the library for non normalized problems.

**Comment by benneti** [comment]
Oh that is cool to know, would you say the best learning source is the official docs. Because for now I just tried stuff and read a few parts of the doc and the wiki book.

**Comment by antoine-levitt** [comment]
More code, more bugs, more stuff to document and change if we change an API. But sure, if you feel it's useful, can you make a PR? Don't forget `project_tangent` as well.
